name: report
on:
  workflow_run:
    workflows: [ test ]
    types: [ completed ]

permissions:
  checks: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: /test-results-(.*)/
        name: 'Test report $1'
        path: result.xml
        reporter: java-junit
